-- Query: Multiple constraints
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
USE hbtn_0d_usa;

CREATE TABLE IF NOT EXISTS cities (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	state_id NOT NULL FOREIGN KEY REFERENCES states(id)
	name VARCHAR(256) NOT NULL,
);
